<?php

declare(strict_types=1);

/**
 * Basic model behaviour: create + retrieve each model, confirm the uuid PK, the
 * BelongsToTenant tenant-stamp, and the declared casts (points_awarded → int,
 * earned_at → Carbon) round-trip through the database.
 */

use Illuminate\Support\Carbon;
use Illuminate\Support\Str;
use Vctrs\Plugins\VbGratitude\Models\GratitudeBadgeAward;
use Vctrs\Plugins\VbGratitude\Models\GratitudeShoutout;

require_once __DIR__.'/bootstrap.php';

beforeEach(function () {
    pluginRunMigrations();
    pluginBindTenant('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa');
});

it('creates and retrieves a shoutout with a uuid key and int cast', function () {
    $shoutout = GratitudeShoutout::create([
        'giver_user_id' => (string) Str::uuid(),
        'recipient_staff_id' => (string) Str::uuid(),
        'message' => 'Great work on the audit.',
        'category' => 'quality',
        'points_awarded' => '15', // string in → int out proves the cast
    ]);

    // uuid PK auto-generated by HasStringUuid (non-incrementing string key).
    expect($shoutout->getKeyName())->toBe('id')
        ->and($shoutout->incrementing)->toBeFalse()
        ->and($shoutout->getKeyType())->toBe('string')
        ->and($shoutout->id)->toBeString()
        ->and(strlen((string) $shoutout->id))->toBe(36);

    $fresh = GratitudeShoutout::find($shoutout->id);

    expect($fresh)->not->toBeNull()
        ->and($fresh->message)->toBe('Great work on the audit.')
        ->and($fresh->points_awarded)->toBe(15) // cast to int
        ->and($fresh->tenant_id)->toBe(PLUGIN_TEST_TENANT);
});

it('creates and retrieves a badge award with a datetime cast', function () {
    $award = GratitudeBadgeAward::create([
        'user_id' => (string) Str::uuid(),
        'badge_key' => 'top_helper',
        'earned_at' => '2026-08-16 12:00:00',
    ]);

    $fresh = GratitudeBadgeAward::find($award->id);

    expect($fresh)->not->toBeNull()
        ->and($fresh->badge_key)->toBe('top_helper')
        ->and($fresh->earned_at)->toBeInstanceOf(Carbon::class)
        ->and($fresh->earned_at->format('Y-m-d H:i:s'))->toBe('2026-08-16 12:00:00')
        ->and($fresh->tenant_id)->toBe(PLUGIN_TEST_TENANT);
});
